# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ajitcool19.github.io/try_out_demo/"

git_url = "https://github.com/ajitcool19/try_out_demo/tree/master/"

def custom_doc_links(name): return None
